services:
  - type: web
    name: phishing-detector
    env: python
    buildCommand: pip install --prefer-binary -r requirements.txt && python train.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
